modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/CookieJarModding/Assembly/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "CookieJar Modding"
credits = "JustinPlayzz, Uraneptus, ebo2022"
description = "Adds more unique building blocks to Minecraft."
#displayURL = "https://www.moonflower.gg"
#updateJSONURL = ""
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
mandatory = true
versionRange = "[4.10.88,)"
ordering = "AFTER"
side = "BOTH"